[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200

lib_deps =
    bblanchon/ArduinoJson@^7.0.0
    zinggjm/GxEPD2@^1.5.2

build_flags =
    -D LOCAL_SSID=\"WiMagneFi2.4\"
    -D LOCAL_PASS=\"MagneWifi123\"
    -D AWS_API_KEY=\"lkjhfdgsl234asdgf_asdfg\"
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1